//
// Qt5xHb - Bindings libraries for Harbour/xHarbour and Qt Framework 5
//
// Copyright (c) 2025 Marcos Antonio Gambeta <marcosgambeta@outlook.com>
//

// DO NOT EDIT THIS FILE - the content was created using a source code generator

// clang-format off

#include <hbclass.ch>

#ifndef QT5XHB_NO_REQUESTS
#endif

CLASS QCameraLocksControl INHERIT QMediaControl

   METHOD delete
   METHOD lockStatus
   METHOD searchAndLock
   METHOD supportedLocks
   METHOD unlock

   METHOD onLockStatusChanged

   DESTRUCTOR destroyObject

END CLASS

PROCEDURE destroyObject() CLASS QCameraLocksControl
   IF ::self_destruction
      ::delete()
   ENDIF
RETURN

// clang-format on

#pragma BEGINDUMP

#include <QtCore/Qt>

#ifndef __XHARBOUR__
#include <QtMultimedia/QCameraLocksControl>
#endif

#include "qt5xhb_common.hpp"
#include "qt5xhb_macros.hpp"
#include "qt5xhb_utils.hpp"
#include "qt5xhb_events.hpp"
#include "qt5xhb_signals.hpp"

#ifdef __XHARBOUR__
#include <QtMultimedia/QCameraLocksControl>
#endif

#define GET_PTR_FROM_SELF(p) auto p = qobject_cast<QCameraLocksControl *>(Qt5xHb::getQObjectPointerFromSelfItem())

// ~QCameraLocksControl()
HB_FUNC_STATIC(QCAMERALOCKSCONTROL_DELETE)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
    Qt5xHb::Events_disconnect_all_events(obj, true);
    Qt5xHb::Signals_disconnect_all_signals(obj, true);
    delete obj;
    obj = nullptr;
    auto ptr = hb_itemPutPtr(nullptr, nullptr);
    hb_objSendMsg(hb_stackSelfItem(), "_POINTER", 1, ptr);
    hb_itemRelease(ptr);
  }

  hb_itemReturn(hb_stackSelfItem());
}

// virtual QCamera::LockStatus lockStatus(QCamera::LockType lock) const = 0
HB_FUNC_STATIC(QCAMERALOCKSCONTROL_LOCKSTATUS)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(1) && HB_ISNUM(1)) {
#endif
      RENUM(obj->lockStatus(static_cast<QCamera::LockType>(hb_parni(1))));
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      hb_errRT_BASE(EG_ARG, 3012, nullptr, HB_ERR_FUNCNAME, HB_ERR_ARGS_BASEPARAMS);
    }
#endif
  }
}

// virtual void searchAndLock(QCamera::LockTypes locks) = 0
HB_FUNC_STATIC(QCAMERALOCKSCONTROL_SEARCHANDLOCK)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(1) && HB_ISNUM(1)) {
#endif
      obj->searchAndLock(static_cast<QCamera::LockTypes>(hb_parni(1)));
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      hb_errRT_BASE(EG_ARG, 3012, nullptr, HB_ERR_FUNCNAME, HB_ERR_ARGS_BASEPARAMS);
    }
#endif
  }

  hb_itemReturn(hb_stackSelfItem());
}

// virtual QCamera::LockTypes supportedLocks() const = 0
HB_FUNC_STATIC(QCAMERALOCKSCONTROL_SUPPORTEDLOCKS)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(0)) {
#endif
      RENUM(obj->supportedLocks());
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      hb_errRT_BASE(EG_ARG, 3012, nullptr, HB_ERR_FUNCNAME, HB_ERR_ARGS_BASEPARAMS);
    }
#endif
  }
}

// virtual void unlock(QCamera::LockTypes locks) = 0
HB_FUNC_STATIC(QCAMERALOCKSCONTROL_UNLOCK)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(1) && HB_ISNUM(1)) {
#endif
      obj->unlock(static_cast<QCamera::LockTypes>(hb_parni(1)));
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      hb_errRT_BASE(EG_ARG, 3012, nullptr, HB_ERR_FUNCNAME, HB_ERR_ARGS_BASEPARAMS);
    }
#endif
  }

  hb_itemReturn(hb_stackSelfItem());
}

// void lockStatusChanged(QCamera::LockType lock, QCamera::LockStatus status, QCamera::LockChangeReason reason)
HB_FUNC_STATIC(QCAMERALOCKSCONTROL_ONLOCKSTATUSCHANGED)
{
  GET_PTR_FROM_SELF(sender);

  auto result = false;

  if (sender != nullptr) {
    auto indexOfSignal = sender->metaObject()->indexOfSignal(
        "lockStatusChanged(QCamera::LockType,QCamera::LockStatus,QCamera::LockChangeReason)");
    auto indexOfCodeBlock = -1;

    if (ISNUMPAR(1) && ISBLOCKORSYMBOL(1)) {
      if (Qt5xHb::Signals_connection(sender, indexOfSignal, indexOfCodeBlock)) {
        auto connection = QObject::connect(sender, &QCameraLocksControl::lockStatusChanged,
                                           [sender, indexOfCodeBlock](QCamera::LockType arg1, QCamera::LockStatus arg2,
                                                                      QCamera::LockChangeReason arg3) {
                                             auto cb = Qt5xHb::Signals_return_codeblock(indexOfCodeBlock);

                                             if (cb != nullptr) {
                                               auto pSender =
                                                   Qt5xHb::Signals_return_qobject(sender, "QCAMERALOCKSCONTROL");
                                               auto pArg1 = hb_itemPutNI(nullptr, static_cast<int>(arg1));
                                               auto pArg2 = hb_itemPutNI(nullptr, static_cast<int>(arg2));
                                               auto pArg3 = hb_itemPutNI(nullptr, static_cast<int>(arg3));
                                               hb_vmEvalBlockV(cb, 4, pSender, pArg1, pArg2, pArg3);
                                               hb_itemRelease(pSender);
                                               hb_itemRelease(pArg1);
                                               hb_itemRelease(pArg2);
                                               hb_itemRelease(pArg3);
                                             }
                                           });

        Qt5xHb::Signals_store_connection(indexOfCodeBlock, connection);
        result = true;
      }
    } else if (ISNUMPAR(0)) {
      Qt5xHb::Signals_disconnection(sender, indexOfSignal);
      QObject::disconnect(Qt5xHb::Signals_get_connection(sender, indexOfSignal));
      result = true;
    } else {
      hb_errRT_BASE(EG_ARG, 3012, nullptr, HB_ERR_FUNCNAME, HB_ERR_ARGS_BASEPARAMS);
    }
  }

  hb_retl(result);
}

#pragma ENDDUMP
