//
// Qt5xHb - Bindings libraries for Harbour/xHarbour and Qt Framework 5
//
// Copyright (c) 2026 Marcos Antonio Gambeta <marcosgambeta@outlook.com>
//

// DO NOT EDIT THIS FILE - the content was created using a source code generator

// clang-format off

#include <hbclass.ch>

#ifndef QT5XHB_NO_REQUESTS
#endif

CLASS QMediaTimeInterval

   DATA pointer
   DATA self_destruction INIT .F.

   METHOD new
   METHOD delete
   METHOD contains
   METHOD end
   METHOD isNormal
   METHOD normalized
   METHOD start
   METHOD translated

   METHOD newFrom
   METHOD newFromObject
   METHOD newFromPointer
   METHOD selfDestruction
   METHOD setSelfDestruction

   DESTRUCTOR destroyObject

ENDCLASS

PROCEDURE destroyObject() CLASS QMediaTimeInterval
   IF ::self_destruction
      ::delete()
   ENDIF
RETURN

// clang-format on

#pragma BEGINDUMP

#include <QtCore/Qt>

#ifndef __XHARBOUR__
#include <QtMultimedia/QMediaTimeInterval>
#endif

#include "qt5xhb_common.hpp"
#include "qt5xhb_macros.hpp"
#include "qt5xhb_utils.hpp"

#ifdef __XHARBOUR__
#include <QtMultimedia/QMediaTimeInterval>
#endif

#define GET_PTR_FROM_SELF(p) auto p = static_cast<QMediaTimeInterval *>(Qt5xHb::itemGetPtrStackSelfItem())

HB_FUNC_STATIC(QMEDIATIMEINTERVAL_NEW)
{
  if (ISNUMPAR(0)) {
    // QMediaTimeInterval()
    auto obj = new QMediaTimeInterval();
    Qt5xHb::returnNewObject(obj, true);
  } else if (ISNUMPAR(2) && HB_ISNUM(1) && HB_ISNUM(2)) {
    // QMediaTimeInterval(qint64 start, qint64 end)
    auto obj = new QMediaTimeInterval(PQINT64(1), PQINT64(2));
    Qt5xHb::returnNewObject(obj, true);
  } else if (ISNUMPAR(1) && ISQMEDIATIMEINTERVAL(1)) {
    // QMediaTimeInterval(const QMediaTimeInterval &other)
    auto obj = new QMediaTimeInterval(*PQMEDIATIMEINTERVAL(1));
    Qt5xHb::returnNewObject(obj, true);
  } else {
    THROW_ERROR_3012();
  }
}

HB_FUNC_STATIC(QMEDIATIMEINTERVAL_DELETE)
{
  GET_PTR_FROM_SELF(obj);
  DELETE_OBJECT(obj);
  RETURN_SELF();
}

// bool contains(qint64 time) const
HB_FUNC_STATIC(QMEDIATIMEINTERVAL_CONTAINS)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(1) && HB_ISNUM(1)) {
#endif
      RBOOL(obj->contains(PQINT64(1)));
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      THROW_ERROR_3012();
    }
#endif
  }
}

// qint64 end() const
HB_FUNC_STATIC(QMEDIATIMEINTERVAL_END)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(0)) {
#endif
      RQINT64(obj->end());
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      THROW_ERROR_3012();
    }
#endif
  }
}

// bool isNormal() const
HB_FUNC_STATIC(QMEDIATIMEINTERVAL_ISNORMAL)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(0)) {
#endif
      RBOOL(obj->isNormal());
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      THROW_ERROR_3012();
    }
#endif
  }
}

// QMediaTimeInterval normalized() const
HB_FUNC_STATIC(QMEDIATIMEINTERVAL_NORMALIZED)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(0)) {
#endif
      RQMEDIATIMEINTERVAL(obj->normalized());
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      THROW_ERROR_3012();
    }
#endif
  }
}

// qint64 start() const
HB_FUNC_STATIC(QMEDIATIMEINTERVAL_START)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(0)) {
#endif
      RQINT64(obj->start());
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      THROW_ERROR_3012();
    }
#endif
  }
}

// QMediaTimeInterval translated(qint64 offset) const
HB_FUNC_STATIC(QMEDIATIMEINTERVAL_TRANSLATED)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(1) && HB_ISNUM(1)) {
#endif
      RQMEDIATIMEINTERVAL(obj->translated(PQINT64(1)));
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      THROW_ERROR_3012();
    }
#endif
  }
}

HB_FUNC_STATIC(QMEDIATIMEINTERVAL_NEWFROM)
{
  NEWFROM();
}

HB_FUNC_STATIC(QMEDIATIMEINTERVAL_NEWFROMOBJECT)
{
  HB_FUNC_EXEC(QMEDIATIMEINTERVAL_NEWFROM);
}

HB_FUNC_STATIC(QMEDIATIMEINTERVAL_NEWFROMPOINTER)
{
  HB_FUNC_EXEC(QMEDIATIMEINTERVAL_NEWFROM);
}

HB_FUNC_STATIC(QMEDIATIMEINTERVAL_SELFDESTRUCTION)
{
  SELFDESTRUCTION();
}

HB_FUNC_STATIC(QMEDIATIMEINTERVAL_SETSELFDESTRUCTION)
{
  SETSELFDESTRUCTION();
}

#pragma ENDDUMP
