//
// Qt5xHb - Bindings libraries for Harbour/xHarbour and Qt Framework 5
//
// Copyright (c) 2026 Marcos Antonio Gambeta <marcosgambeta@outlook.com>
//

// DO NOT EDIT THIS FILE - the content was created using a source code generator

// clang-format off

#include <hbclass.ch>

#ifndef QT5XHB_NO_REQUESTS
REQUEST QIcon
REQUEST QPalette
REQUEST QPixmap
REQUEST QRect
REQUEST QSize
REQUEST QStyle
#endif

CLASS QProxyStyle INHERIT QCommonStyle

   METHOD new
   METHOD delete
   METHOD baseStyle
   METHOD setBaseStyle
   METHOD drawPrimitive
   METHOD drawControl
   METHOD drawComplexControl
   METHOD drawItemText
   METHOD drawItemPixmap
   METHOD sizeFromContents
   METHOD subElementRect
   METHOD subControlRect
   METHOD itemTextRect
   METHOD itemPixmapRect
   METHOD hitTestComplexControl
   METHOD styleHint
   METHOD pixelMetric
   METHOD layoutSpacing
   METHOD standardIcon
   METHOD standardPixmap
   METHOD generatedIconPixmap
   METHOD standardPalette
   METHOD polish
   METHOD unpolish

   DESTRUCTOR destroyObject

ENDCLASS

PROCEDURE destroyObject() CLASS QProxyStyle
   IF ::self_destruction
      ::delete()
   ENDIF
RETURN

// clang-format on

#pragma BEGINDUMP

#include <QtCore/Qt>

#ifndef __XHARBOUR__
#include <QtWidgets/QProxyStyle>
#endif

#include "qt5xhb_common.hpp"
#include "qt5xhb_macros.hpp"
#include "qt5xhb_utils.hpp"
#include "qt5xhb_events.hpp"
#include "qt5xhb_signals.hpp"

#ifdef __XHARBOUR__
#include <QtWidgets/QProxyStyle>
#endif

#define GET_PTR_FROM_SELF(p) auto p = qobject_cast<QProxyStyle *>(Qt5xHb::getQObjectPointerFromSelfItem())

HB_FUNC_STATIC(QPROXYSTYLE_NEW)
{
  if (ISBETWEEN(0, 1) && ISOBJECTORNIL(1)) {
    // QProxyStyle(QStyle *style = nullptr)
    auto obj = new QProxyStyle(OPQSTYLE(1, nullptr));
    Qt5xHb::returnNewObject(obj, false);

  } else if (ISNUMPAR(1) && HB_ISCHAR(1)) {
    // QProxyStyle(const QString &key)
    auto obj = new QProxyStyle(PQSTRING(1));
    Qt5xHb::returnNewObject(obj, false);

  } else {
    THROW_ERROR_3012();
  }
}

HB_FUNC_STATIC(QPROXYSTYLE_DELETE)
{
  GET_PTR_FROM_SELF(obj);
  DELETE_QOBJECT(obj);
  RETURN_SELF();
}

// QStyle *baseStyle() const
HB_FUNC_STATIC(QPROXYSTYLE_BASESTYLE)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(0)) {
#endif
      auto ptr = obj->baseStyle();
      Qt5xHb::createReturnQObjectClass(ptr, "QSTYLE");
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      THROW_ERROR_3012();
    }
#endif
  }
}

// void setBaseStyle(QStyle *style)
HB_FUNC_STATIC(QPROXYSTYLE_SETBASESTYLE)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(1) && ISQSTYLE(1)) {
#endif
      obj->setBaseStyle(PQSTYLE(1));
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      THROW_ERROR_3012();
    }
#endif
  }

  RETURN_SELF();
}

// void drawPrimitive(QStyle::PrimitiveElement element, const QStyleOption *option, QPainter *painter, const QWidget
// *widget = nullptr) const
HB_FUNC_STATIC(QPROXYSTYLE_DRAWPRIMITIVE)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISBETWEEN(3, 4) && HB_ISNUM(1) && ISQSTYLEOPTION(2) && ISQPAINTER(3) && ISQWIDGETORNIL(4)) {
#endif
      obj->drawPrimitive(PQSTYLE_PRIMITIVEELEMENT(1), PQSTYLEOPTION(2), PQPAINTER(3), OPQWIDGET(4, nullptr));
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      THROW_ERROR_3012();
    }
#endif
  }

  RETURN_SELF();
}

// void drawControl(QStyle::ControlElement element, const QStyleOption *option, QPainter *painter, const QWidget *widget
// = nullptr) const
HB_FUNC_STATIC(QPROXYSTYLE_DRAWCONTROL)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISBETWEEN(3, 4) && HB_ISNUM(1) && ISQSTYLEOPTION(2) && ISQPAINTER(3) && ISQWIDGETORNIL(4)) {
#endif
      obj->drawControl(PQSTYLE_CONTROLELEMENT(1), PQSTYLEOPTION(2), PQPAINTER(3), OPQWIDGET(4, nullptr));
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      THROW_ERROR_3012();
    }
#endif
  }

  RETURN_SELF();
}

// void drawComplexControl(QStyle::ComplexControl control, const QStyleOptionComplex *option, QPainter *painter, const
// QWidget *widget = nullptr) const
HB_FUNC_STATIC(QPROXYSTYLE_DRAWCOMPLEXCONTROL)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISBETWEEN(3, 4) && HB_ISNUM(1) && ISQSTYLEOPTIONCOMPLEX(2) && ISQPAINTER(3) && ISQWIDGETORNIL(4)) {
#endif
      obj->drawComplexControl(PQSTYLE_COMPLEXCONTROL(1), PQSTYLEOPTIONCOMPLEX(2), PQPAINTER(3), OPQWIDGET(4, nullptr));
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      THROW_ERROR_3012();
    }
#endif
  }

  RETURN_SELF();
}

// void drawItemText(QPainter *painter, const QRect &rect, int flags, const QPalette &pal, bool enabled, const QString
// &text, QPalette::ColorRole textRole = QPalette::NoRole) const
HB_FUNC_STATIC(QPROXYSTYLE_DRAWITEMTEXT)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISBETWEEN(6, 7) && ISQPAINTER(1) && ISQRECT(2) && HB_ISNUM(3) && ISQPALETTE(4) && ISBOOL(5) && HB_ISCHAR(6) &&
        ISNUMORNIL(7)) {
#endif
      obj->drawItemText(PQPAINTER(1), *PQRECT(2), PINT(3), *PQPALETTE(4), PBOOL(5), PQSTRING(6),
                        HB_ISNIL(7) ? QPalette::NoRole : PQPALETTE_COLORROLE(7));
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      THROW_ERROR_3012();
    }
#endif
  }

  RETURN_SELF();
}

// virtual void drawItemPixmap(QPainter *painter, const QRect &rect, int alignment, const QPixmap &pixmap) const
HB_FUNC_STATIC(QPROXYSTYLE_DRAWITEMPIXMAP)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(4) && ISQPAINTER(1) && ISQRECT(2) && HB_ISNUM(3) && ISQPIXMAP(4)) {
#endif
      obj->drawItemPixmap(PQPAINTER(1), *PQRECT(2), PINT(3), *PQPIXMAP(4));
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      THROW_ERROR_3012();
    }
#endif
  }

  RETURN_SELF();
}

// QSize sizeFromContents(QStyle::ContentsType type, const QStyleOption *option, const QSize &size, const QWidget
// *widget) const
HB_FUNC_STATIC(QPROXYSTYLE_SIZEFROMCONTENTS)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(4) && HB_ISNUM(1) && ISQSTYLEOPTION(2) && ISQSIZE(3) && ISQWIDGET(4)) {
#endif
      RQSIZE(obj->sizeFromContents(PQSTYLE_CONTENTSTYPE(1), PQSTYLEOPTION(2), *PQSIZE(3), PQWIDGET(4)));
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      THROW_ERROR_3012();
    }
#endif
  }
}

// QRect subElementRect(QStyle::SubElement element, const QStyleOption *option, const QWidget *widget) const
HB_FUNC_STATIC(QPROXYSTYLE_SUBELEMENTRECT)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(3) && HB_ISNUM(1) && ISQSTYLEOPTION(2) && ISQWIDGET(3)) {
#endif
      RQRECT(obj->subElementRect(PQSTYLE_SUBELEMENT(1), PQSTYLEOPTION(2), PQWIDGET(3)));
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      THROW_ERROR_3012();
    }
#endif
  }
}

// QRect subControlRect(QStyle::ComplexControl cc, const QStyleOptionComplex *opt, QStyle::SubControl sc, const QWidget
// *widget) const
HB_FUNC_STATIC(QPROXYSTYLE_SUBCONTROLRECT)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(4) && HB_ISNUM(1) && ISQSTYLEOPTIONCOMPLEX(2) && HB_ISNUM(3) && ISQWIDGET(4)) {
#endif
      RQRECT(
          obj->subControlRect(PQSTYLE_COMPLEXCONTROL(1), PQSTYLEOPTIONCOMPLEX(2), PQSTYLE_SUBCONTROL(3), PQWIDGET(4)));
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      THROW_ERROR_3012();
    }
#endif
  }
}

// QRect itemTextRect(const QFontMetrics &fm, const QRect &r, int flags, bool enabled, const QString &text) const
HB_FUNC_STATIC(QPROXYSTYLE_ITEMTEXTRECT)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(5) && ISQFONTMETRICS(1) && ISQRECT(2) && HB_ISNUM(3) && ISBOOL(4) && HB_ISCHAR(5)) {
#endif
      RQRECT(obj->itemTextRect(*PQFONTMETRICS(1), *PQRECT(2), PINT(3), PBOOL(4), PQSTRING(5)));
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      THROW_ERROR_3012();
    }
#endif
  }
}

// QRect itemPixmapRect(const QRect &r, int flags, const QPixmap &pixmap) const
HB_FUNC_STATIC(QPROXYSTYLE_ITEMPIXMAPRECT)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(3) && ISQRECT(1) && HB_ISNUM(2) && ISQPIXMAP(3)) {
#endif
      RQRECT(obj->itemPixmapRect(*PQRECT(1), PINT(2), *PQPIXMAP(3)));
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      THROW_ERROR_3012();
    }
#endif
  }
}

// QStyle::SubControl hitTestComplexControl(QStyle::ComplexControl control, const QStyleOptionComplex *option, const
// QPoint &pos, const QWidget *widget = nullptr) const
HB_FUNC_STATIC(QPROXYSTYLE_HITTESTCOMPLEXCONTROL)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISBETWEEN(3, 4) && HB_ISNUM(1) && ISQSTYLEOPTIONCOMPLEX(2) && ISQPOINT(3) && ISQWIDGETORNIL(4)) {
#endif
      RENUM(obj->hitTestComplexControl(PQSTYLE_COMPLEXCONTROL(1), PQSTYLEOPTIONCOMPLEX(2), *PQPOINT(3),
                                       OPQWIDGET(4, nullptr)));
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      THROW_ERROR_3012();
    }
#endif
  }
}

// int styleHint(QStyle::StyleHint hint, const QStyleOption *option = nullptr, const QWidget *widget = nullptr,
// QStyleHintReturn *returnData = nullptr) const
HB_FUNC_STATIC(QPROXYSTYLE_STYLEHINT)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISBETWEEN(1, 4) && HB_ISNUM(1) && ISQSTYLEOPTIONORNIL(2) && ISQWIDGETORNIL(3) && ISQSTYLEHINTRETURNORNIL(4)) {
#endif
      RINT(obj->styleHint(PQSTYLE_STYLEHINT(1), HB_ISNIL(2) ? nullptr : PQSTYLEOPTION(2), OPQWIDGET(3, nullptr),
                          HB_ISNIL(4) ? nullptr : PQSTYLEHINTRETURN(4)));
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      THROW_ERROR_3012();
    }
#endif
  }
}

// int pixelMetric(QStyle::PixelMetric metric, const QStyleOption *option = nullptr, const QWidget *widget = nullptr)
// const
HB_FUNC_STATIC(QPROXYSTYLE_PIXELMETRIC)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISBETWEEN(1, 3) && HB_ISNUM(1) && ISQSTYLEOPTIONORNIL(2) && ISQWIDGETORNIL(3)) {
#endif
      RINT(obj->pixelMetric(PQSTYLE_PIXELMETRIC(1), HB_ISNIL(2) ? nullptr : PQSTYLEOPTION(2), OPQWIDGET(3, nullptr)));
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      THROW_ERROR_3012();
    }
#endif
  }
}

// int layoutSpacing(QSizePolicy::ControlType control1, QSizePolicy::ControlType control2, Qt::Orientation orientation,
// const QStyleOption *option = nullptr, const QWidget *widget = nullptr) const
HB_FUNC_STATIC(QPROXYSTYLE_LAYOUTSPACING)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISBETWEEN(3, 5) && HB_ISNUM(1) && HB_ISNUM(2) && HB_ISNUM(3) && ISQSTYLEOPTIONORNIL(4) && ISQWIDGETORNIL(5)) {
#endif
      RINT(obj->layoutSpacing(PQSIZEPOLICY_CONTROLTYPE(1), PQSIZEPOLICY_CONTROLTYPE(2), PQT_ORIENTATION(3),
                              HB_ISNIL(4) ? nullptr : PQSTYLEOPTION(4), OPQWIDGET(5, nullptr)));
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      THROW_ERROR_3012();
    }
#endif
  }
}

// QIcon standardIcon(QStyle::StandardPixmap standardIcon, const QStyleOption *option = nullptr, const QWidget *widget =
// nullptr) const
HB_FUNC_STATIC(QPROXYSTYLE_STANDARDICON)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISBETWEEN(1, 3) && HB_ISNUM(1) && ISQSTYLEOPTIONORNIL(2) && ISQWIDGETORNIL(3)) {
#endif
      RQICON(obj->standardIcon(PQSTYLE_STANDARDPIXMAP(1), HB_ISNIL(2) ? nullptr : PQSTYLEOPTION(2),
                               OPQWIDGET(3, nullptr)));
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      THROW_ERROR_3012();
    }
#endif
  }
}

// QPixmap standardPixmap(QStyle::StandardPixmap standardPixmap, const QStyleOption *opt, const QWidget *widget =
// nullptr) const
HB_FUNC_STATIC(QPROXYSTYLE_STANDARDPIXMAP)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISBETWEEN(2, 3) && HB_ISNUM(1) && ISQSTYLEOPTION(2) && ISQWIDGETORNIL(3)) {
#endif
      RQPIXMAP(obj->standardPixmap(PQSTYLE_STANDARDPIXMAP(1), PQSTYLEOPTION(2), OPQWIDGET(3, nullptr)));
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      THROW_ERROR_3012();
    }
#endif
  }
}

// QPixmap generatedIconPixmap(QIcon::Mode iconMode, const QPixmap &pixmap, const QStyleOption *opt) const
HB_FUNC_STATIC(QPROXYSTYLE_GENERATEDICONPIXMAP)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(3) && HB_ISNUM(1) && ISQPIXMAP(2) && ISQSTYLEOPTION(3)) {
#endif
      RQPIXMAP(obj->generatedIconPixmap(PQICON_MODE(1), *PQPIXMAP(2), PQSTYLEOPTION(3)));
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      THROW_ERROR_3012();
    }
#endif
  }
}

// QPalette standardPalette() const
HB_FUNC_STATIC(QPROXYSTYLE_STANDARDPALETTE)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(0)) {
#endif
      RQPALETTE(obj->standardPalette());
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      THROW_ERROR_3012();
    }
#endif
  }
}

HB_FUNC_STATIC(QPROXYSTYLE_POLISH)
{
  if (ISNUMPAR(1) && ISQWIDGET(1)) {
    // void polish(QWidget *widget)
    GET_PTR_FROM_SELF(obj);

    if (obj != nullptr) {
      obj->polish(PQWIDGET(1));
    }

    RETURN_SELF();

  } else if (ISNUMPAR(1) && ISQPALETTE(1)) {
    // void polish(QPalette &pal)
    GET_PTR_FROM_SELF(obj);

    if (obj != nullptr) {
      obj->polish(*PQPALETTE(1));
    }

    RETURN_SELF();

  } else if (ISNUMPAR(1) && ISQAPPLICATION(1)) {
    // void polish(QApplication *app)
    GET_PTR_FROM_SELF(obj);

    if (obj != nullptr) {
      obj->polish(PQAPPLICATION(1));
    }

    RETURN_SELF();

  } else {
    THROW_ERROR_3012();
  }
}

HB_FUNC_STATIC(QPROXYSTYLE_UNPOLISH)
{
  if (ISNUMPAR(1) && ISQWIDGET(1)) {
    // void unpolish(QWidget *widget)
    GET_PTR_FROM_SELF(obj);

    if (obj != nullptr) {
      obj->unpolish(PQWIDGET(1));
    }

    RETURN_SELF();

  } else if (ISNUMPAR(1) && ISQAPPLICATION(1)) {
    // void unpolish(QApplication *app)
    GET_PTR_FROM_SELF(obj);

    if (obj != nullptr) {
      obj->unpolish(PQAPPLICATION(1));
    }

    RETURN_SELF();

  } else {
    THROW_ERROR_3012();
  }
}

#pragma ENDDUMP
