//
// Qt5xHb - Bindings libraries for Harbour/xHarbour and Qt Framework 5
//
// Copyright (c) 2026 Marcos Antonio Gambeta <marcosgambeta@outlook.com>
//

// DO NOT EDIT THIS FILE - the content was created using a source code generator

// clang-format off

#include <hbclass.ch>

#ifndef QT5XHB_NO_REQUESTS
#endif

CLASS QVBoxLayout INHERIT QBoxLayout

   METHOD new
   METHOD delete

   DESTRUCTOR destroyObject

ENDCLASS

PROCEDURE destroyObject() CLASS QVBoxLayout
   IF ::self_destruction
      ::delete()
   ENDIF
RETURN

// clang-format on

#pragma BEGINDUMP

#include <QtCore/Qt>

#ifndef __XHARBOUR__
#include <QtWidgets/QVBoxLayout>
#endif

#include "qt5xhb_common.hpp"
#include "qt5xhb_macros.hpp"
#include "qt5xhb_utils.hpp"
#include "qt5xhb_events.hpp"
#include "qt5xhb_signals.hpp"

#ifdef __XHARBOUR__
#include <QtWidgets/QVBoxLayout>
#endif

#define GET_PTR_FROM_SELF(p) auto p = qobject_cast<QVBoxLayout *>(Qt5xHb::getQObjectPointerFromSelfItem())

HB_FUNC_STATIC(QVBOXLAYOUT_NEW)
{
  if (ISNUMPAR(0)) {
    // QVBoxLayout()
    auto obj = new QVBoxLayout();
    Qt5xHb::returnNewObject(obj, false);

  } else if (ISNUMPAR(1) && ISQWIDGET(1)) {
    // QVBoxLayout(QWidget *parent)
    auto obj = new QVBoxLayout(PQWIDGET(1));
    Qt5xHb::returnNewObject(obj, false);

  } else {
    THROW_ERROR_3012();
  }
}

HB_FUNC_STATIC(QVBOXLAYOUT_DELETE)
{
  GET_PTR_FROM_SELF(obj);
  DELETE_QOBJECT(obj);
  RETURN_SELF();
}

#pragma ENDDUMP
