//
// Qt5xHb - Bindings libraries for Harbour/xHarbour and Qt Framework 5
//
// Copyright (c) 2026 Marcos Antonio Gambeta <marcosgambeta@outlook.com>
//

// DO NOT EDIT THIS FILE - the content was created using a source code generator

// clang-format off

#include <hbclass.ch>

#ifndef QT5XHB_NO_REQUESTS
REQUEST QDBusError
REQUEST QDBusMessage
#endif

CLASS QDBusPendingCall

   DATA pointer
   DATA self_destruction INIT .F.

   METHOD new
   METHOD delete
   METHOD swap
   METHOD isFinished
   METHOD waitForFinished
   METHOD isError
   METHOD isValid
   METHOD error
   METHOD reply
   METHOD fromError
   METHOD fromCompletedCall

   METHOD newFrom
   METHOD newFromObject
   METHOD newFromPointer
   METHOD selfDestruction
   METHOD setSelfDestruction

   DESTRUCTOR destroyObject

ENDCLASS

PROCEDURE destroyObject() CLASS QDBusPendingCall
   IF ::self_destruction
      ::delete()
   ENDIF
RETURN

// clang-format on

#pragma BEGINDUMP

#include <QtCore/Qt>

#ifndef __XHARBOUR__
#include <QtDBus/QDBusPendingCall>
#endif

#include "qt5xhb_common.hpp"
#include "qt5xhb_macros.hpp"
#include "qt5xhb_utils.hpp"

#ifdef __XHARBOUR__
#include <QtDBus/QDBusPendingCall>
#endif

#define GET_PTR_FROM_SELF(p) auto p = static_cast<QDBusPendingCall *>(Qt5xHb::itemGetPtrStackSelfItem())

// QDBusPendingCall(const QDBusPendingCall &other)
HB_FUNC_STATIC(QDBUSPENDINGCALL_NEW)
{
  if (ISNUMPAR(1) && ISQDBUSPENDINGCALL(1)) {
    auto obj = new QDBusPendingCall(*PQDBUSPENDINGCALL(1));
    Qt5xHb::returnNewObject(obj, true);
  } else {
    hb_errRT_BASE(EG_ARG, 3012, nullptr, HB_ERR_FUNCNAME, HB_ERR_ARGS_BASEPARAMS);
  }
}

HB_FUNC_STATIC(QDBUSPENDINGCALL_DELETE)
{
  GET_PTR_FROM_SELF(obj);
  DELETE_OBJECT(obj);
  RETURN_SELF();
}

// void swap(QDBusPendingCall &other)
HB_FUNC_STATIC(QDBUSPENDINGCALL_SWAP)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(1) && ISQDBUSPENDINGCALL(1)) {
#endif
      obj->swap(*PQDBUSPENDINGCALL(1));
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      hb_errRT_BASE(EG_ARG, 3012, nullptr, HB_ERR_FUNCNAME, HB_ERR_ARGS_BASEPARAMS);
    }
#endif
  }

  RETURN_SELF();
}

// bool isFinished() const
HB_FUNC_STATIC(QDBUSPENDINGCALL_ISFINISHED)
{
#ifndef Q_QDOC
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(0)) {
#endif
      RBOOL(obj->isFinished());
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      hb_errRT_BASE(EG_ARG, 3012, nullptr, HB_ERR_FUNCNAME, HB_ERR_ARGS_BASEPARAMS);
    }
#endif
  }
#endif
}

// void waitForFinished()
HB_FUNC_STATIC(QDBUSPENDINGCALL_WAITFORFINISHED)
{
#ifndef Q_QDOC
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(0)) {
#endif
      obj->waitForFinished();
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      hb_errRT_BASE(EG_ARG, 3012, nullptr, HB_ERR_FUNCNAME, HB_ERR_ARGS_BASEPARAMS);
    }
#endif
  }

  RETURN_SELF();
#endif
}

// bool isError() const
HB_FUNC_STATIC(QDBUSPENDINGCALL_ISERROR)
{
#ifndef Q_QDOC
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(0)) {
#endif
      RBOOL(obj->isError());
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      hb_errRT_BASE(EG_ARG, 3012, nullptr, HB_ERR_FUNCNAME, HB_ERR_ARGS_BASEPARAMS);
    }
#endif
  }
#endif
}

// bool isValid() const
HB_FUNC_STATIC(QDBUSPENDINGCALL_ISVALID)
{
#ifndef Q_QDOC
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(0)) {
#endif
      RBOOL(obj->isValid());
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      hb_errRT_BASE(EG_ARG, 3012, nullptr, HB_ERR_FUNCNAME, HB_ERR_ARGS_BASEPARAMS);
    }
#endif
  }
#endif
}

// QDBusError error() const
HB_FUNC_STATIC(QDBUSPENDINGCALL_ERROR)
{
#ifndef Q_QDOC
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(0)) {
#endif
      RQDBUSERROR(obj->error());
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      hb_errRT_BASE(EG_ARG, 3012, nullptr, HB_ERR_FUNCNAME, HB_ERR_ARGS_BASEPARAMS);
    }
#endif
  }
#endif
}

// QDBusMessage reply() const
HB_FUNC_STATIC(QDBUSPENDINGCALL_REPLY)
{
#ifndef Q_QDOC
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(0)) {
#endif
      RQDBUSMESSAGE(obj->reply());
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      hb_errRT_BASE(EG_ARG, 3012, nullptr, HB_ERR_FUNCNAME, HB_ERR_ARGS_BASEPARAMS);
    }
#endif
  }
#endif
}

// static QDBusPendingCall fromError(const QDBusError &error)
HB_FUNC_STATIC(QDBUSPENDINGCALL_FROMERROR)
{
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
  if (ISNUMPAR(1) && ISQDBUSERROR(1)) {
#endif
    RQDBUSPENDINGCALL(QDBusPendingCall::fromError(*PQDBUSERROR(1)));
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
  } else {
    hb_errRT_BASE(EG_ARG, 3012, nullptr, HB_ERR_FUNCNAME, HB_ERR_ARGS_BASEPARAMS);
  }
#endif
}

// static QDBusPendingCall fromCompletedCall(const QDBusMessage &message)
HB_FUNC_STATIC(QDBUSPENDINGCALL_FROMCOMPLETEDCALL)
{
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
  if (ISNUMPAR(1) && ISQDBUSMESSAGE(1)) {
#endif
    RQDBUSPENDINGCALL(QDBusPendingCall::fromCompletedCall(*PQDBUSMESSAGE(1)));
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
  } else {
    hb_errRT_BASE(EG_ARG, 3012, nullptr, HB_ERR_FUNCNAME, HB_ERR_ARGS_BASEPARAMS);
  }
#endif
}

HB_FUNC_STATIC(QDBUSPENDINGCALL_NEWFROM)
{
  NEWFROM();
}

HB_FUNC_STATIC(QDBUSPENDINGCALL_NEWFROMOBJECT)
{
  HB_FUNC_EXEC(QDBUSPENDINGCALL_NEWFROM);
}

HB_FUNC_STATIC(QDBUSPENDINGCALL_NEWFROMPOINTER)
{
  HB_FUNC_EXEC(QDBUSPENDINGCALL_NEWFROM);
}

HB_FUNC_STATIC(QDBUSPENDINGCALL_SELFDESTRUCTION)
{
  SELFDESTRUCTION();
}

HB_FUNC_STATIC(QDBUSPENDINGCALL_SETSELFDESTRUCTION)
{
  SETSELFDESTRUCTION();
}

#pragma ENDDUMP
