//
// Qt5xHb - Bindings libraries for Harbour/xHarbour and Qt Framework 5
//
// Copyright (c) 2026 Marcos Antonio Gambeta <marcosgambeta@outlook.com>
//

// DO NOT EDIT THIS FILE - the content was created using a source code generator

// clang-format off

#include <hbclass.ch>

#ifndef QT5XHB_NO_REQUESTS
REQUEST QAccessibleInterface
#endif

CLASS QAccessibleTableCellInterface

   DATA pointer
   DATA self_destruction INIT .F.

   METHOD delete
   METHOD columnExtent
   METHOD columnHeaderCells
   METHOD columnIndex
   METHOD rowExtent
   METHOD rowHeaderCells
   METHOD rowIndex
   METHOD isSelected
   METHOD table

   METHOD newFrom
   METHOD newFromObject
   METHOD newFromPointer
   METHOD selfDestruction
   METHOD setSelfDestruction

   DESTRUCTOR destroyObject

ENDCLASS

PROCEDURE destroyObject() CLASS QAccessibleTableCellInterface
   IF ::self_destruction
      ::delete()
   ENDIF
RETURN

// clang-format on

#pragma BEGINDUMP

#include <QtCore/Qt>

#ifndef __XHARBOUR__
#include <QtGui/QAccessibleTableCellInterface>
#endif

#include "qt5xhb_common.hpp"
#include "qt5xhb_macros.hpp"
#include "qt5xhb_utils.hpp"

#ifdef __XHARBOUR__
#include <QtGui/QAccessibleTableCellInterface>
#endif

#define GET_PTR_FROM_SELF(p) auto p = static_cast<QAccessibleTableCellInterface *>(Qt5xHb::itemGetPtrStackSelfItem())

HB_FUNC_STATIC(QACCESSIBLETABLECELLINTERFACE_DELETE)
{
  GET_PTR_FROM_SELF(obj);
  DELETE_OBJECT(obj);
  RETURN_SELF();
}

// virtual int columnExtent() const = 0
HB_FUNC_STATIC(QACCESSIBLETABLECELLINTERFACE_COLUMNEXTENT)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(0)) {
#endif
      RINT(obj->columnExtent());
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      hb_errRT_BASE(EG_ARG, 3012, nullptr, HB_ERR_FUNCNAME, HB_ERR_ARGS_BASEPARAMS);
    }
#endif
  }
}

// virtual QList<QAccessibleInterface *> columnHeaderCells() const = 0
HB_FUNC_STATIC(QACCESSIBLETABLECELLINTERFACE_COLUMNHEADERCELLS)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(0)) {
#endif
      auto list = obj->columnHeaderCells();
      auto pDynSym = hb_dynsymFindName("QACCESSIBLEINTERFACE");
      auto pArray = hb_itemArrayNew(0);
      if (pDynSym != nullptr) {
        for (auto item : list) {
          hb_vmPushDynSym(pDynSym);
          hb_vmPushNil();
          hb_vmDo(0);
          auto pObject = hb_itemNew(nullptr);
          hb_itemCopy(pObject, hb_stackReturnItem());
          auto pItem = hb_itemPutPtr(nullptr, item);
          hb_objSendMsg(pObject, "_POINTER", 1, pItem);
          hb_itemRelease(pItem);
          hb_arrayAddForward(pArray, pObject);
          hb_itemRelease(pObject);
        }
      } else {
        hb_errRT_BASE(EG_NOFUNC, 1001, nullptr, "QACCESSIBLEINTERFACE", HB_ERR_ARGS_BASEPARAMS);
      }
      hb_itemReturnRelease(pArray);
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      hb_errRT_BASE(EG_ARG, 3012, nullptr, HB_ERR_FUNCNAME, HB_ERR_ARGS_BASEPARAMS);
    }
#endif
  }
}

// virtual int columnIndex() const = 0
HB_FUNC_STATIC(QACCESSIBLETABLECELLINTERFACE_COLUMNINDEX)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(0)) {
#endif
      RINT(obj->columnIndex());
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      hb_errRT_BASE(EG_ARG, 3012, nullptr, HB_ERR_FUNCNAME, HB_ERR_ARGS_BASEPARAMS);
    }
#endif
  }
}

// virtual int rowExtent() const = 0
HB_FUNC_STATIC(QACCESSIBLETABLECELLINTERFACE_ROWEXTENT)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(0)) {
#endif
      RINT(obj->rowExtent());
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      hb_errRT_BASE(EG_ARG, 3012, nullptr, HB_ERR_FUNCNAME, HB_ERR_ARGS_BASEPARAMS);
    }
#endif
  }
}

// virtual QList<QAccessibleInterface *> rowHeaderCells() const = 0
HB_FUNC_STATIC(QACCESSIBLETABLECELLINTERFACE_ROWHEADERCELLS)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(0)) {
#endif
      auto list = obj->rowHeaderCells();
      auto pDynSym = hb_dynsymFindName("QACCESSIBLEINTERFACE");
      auto pArray = hb_itemArrayNew(0);
      if (pDynSym != nullptr) {
        for (auto item : list) {
          hb_vmPushDynSym(pDynSym);
          hb_vmPushNil();
          hb_vmDo(0);
          auto pObject = hb_itemNew(nullptr);
          hb_itemCopy(pObject, hb_stackReturnItem());
          auto pItem = hb_itemPutPtr(nullptr, item);
          hb_objSendMsg(pObject, "_POINTER", 1, pItem);
          hb_itemRelease(pItem);
          hb_arrayAddForward(pArray, pObject);
          hb_itemRelease(pObject);
        }
      } else {
        hb_errRT_BASE(EG_NOFUNC, 1001, nullptr, "QACCESSIBLEINTERFACE", HB_ERR_ARGS_BASEPARAMS);
      }
      hb_itemReturnRelease(pArray);
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      hb_errRT_BASE(EG_ARG, 3012, nullptr, HB_ERR_FUNCNAME, HB_ERR_ARGS_BASEPARAMS);
    }
#endif
  }
}

// virtual int rowIndex() const = 0
HB_FUNC_STATIC(QACCESSIBLETABLECELLINTERFACE_ROWINDEX)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(0)) {
#endif
      RINT(obj->rowIndex());
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      hb_errRT_BASE(EG_ARG, 3012, nullptr, HB_ERR_FUNCNAME, HB_ERR_ARGS_BASEPARAMS);
    }
#endif
  }
}

// virtual bool isSelected() const = 0
HB_FUNC_STATIC(QACCESSIBLETABLECELLINTERFACE_ISSELECTED)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(0)) {
#endif
      RBOOL(obj->isSelected());
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      hb_errRT_BASE(EG_ARG, 3012, nullptr, HB_ERR_FUNCNAME, HB_ERR_ARGS_BASEPARAMS);
    }
#endif
  }
}

// virtual QAccessibleInterface *table() const = 0
HB_FUNC_STATIC(QACCESSIBLETABLECELLINTERFACE_TABLE)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(0)) {
#endif
      auto ptr = obj->table();
      Qt5xHb::createReturnClass(ptr, "QACCESSIBLEINTERFACE", false);
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      hb_errRT_BASE(EG_ARG, 3012, nullptr, HB_ERR_FUNCNAME, HB_ERR_ARGS_BASEPARAMS);
    }
#endif
  }
}

HB_FUNC_STATIC(QACCESSIBLETABLECELLINTERFACE_NEWFROM)
{
  NEWFROM();
}

HB_FUNC_STATIC(QACCESSIBLETABLECELLINTERFACE_NEWFROMOBJECT)
{
  HB_FUNC_EXEC(QACCESSIBLETABLECELLINTERFACE_NEWFROM);
}

HB_FUNC_STATIC(QACCESSIBLETABLECELLINTERFACE_NEWFROMPOINTER)
{
  HB_FUNC_EXEC(QACCESSIBLETABLECELLINTERFACE_NEWFROM);
}

HB_FUNC_STATIC(QACCESSIBLETABLECELLINTERFACE_SELFDESTRUCTION)
{
  SELFDESTRUCTION();
}

HB_FUNC_STATIC(QACCESSIBLETABLECELLINTERFACE_SETSELFDESTRUCTION)
{
  SETSELFDESTRUCTION();
}

#pragma ENDDUMP
