//
// Qt5xHb - Bindings libraries for Harbour/xHarbour and Qt Framework 5
//
// Copyright (c) 2026 Marcos Antonio Gambeta <marcosgambeta@outlook.com>
//

// DO NOT EDIT THIS FILE - the content was created using a source code generator

// clang-format off

#include <hbclass.ch>

#ifndef QT5XHB_NO_REQUESTS
#endif

CLASS QIconDragEvent INHERIT QEvent

   METHOD new
   METHOD delete

   DESTRUCTOR destroyObject

ENDCLASS

PROCEDURE destroyObject() CLASS QIconDragEvent
   IF ::self_destruction
      ::delete()
   ENDIF
RETURN

// clang-format on

#pragma BEGINDUMP

#include <QtCore/Qt>

#ifndef __XHARBOUR__
#include <QtGui/QIconDragEvent>
#endif

#include "qt5xhb_common.hpp"
#include "qt5xhb_macros.hpp"
#include "qt5xhb_utils.hpp"

#ifdef __XHARBOUR__
#include <QtGui/QIconDragEvent>
#endif

#define GET_PTR_FROM_SELF(p) auto p = static_cast<QIconDragEvent *>(Qt5xHb::itemGetPtrStackSelfItem())

// QIconDragEvent()
HB_FUNC_STATIC(QICONDRAGEVENT_NEW)
{
  if (ISNUMPAR(0)) {
    auto obj = new QIconDragEvent();
    Qt5xHb::returnNewObject(obj, false);
  } else {
    THROW_ERROR_3012();
  }
}

HB_FUNC_STATIC(QICONDRAGEVENT_DELETE)
{
  GET_PTR_FROM_SELF(obj);
  DELETE_OBJECT(obj);
  RETURN_SELF();
}

#pragma ENDDUMP
