//
// Qt5xHb - Bindings libraries for Harbour/xHarbour and Qt Framework 5
//
// Copyright (c) 2026 Marcos Antonio Gambeta <marcosgambeta@outlook.com>
//

// DO NOT EDIT THIS FILE - the content was created using a source code generator

// clang-format off

#include <hbclass.ch>

#ifndef QT5XHB_NO_REQUESTS
#endif

CLASS QTime

   DATA pointer
   DATA self_destruction INIT .F.

   METHOD new
   METHOD delete
   METHOD addMSecs
   METHOD addSecs
   METHOD elapsed
   METHOD hour
   METHOD isNull
   METHOD isValid
   METHOD minute
   METHOD msec
   METHOD msecsTo
   METHOD restart
   METHOD second
   METHOD secsTo
   METHOD setHMS
   METHOD start
   METHOD toString
   METHOD currentTime
   METHOD fromString

   METHOD newFrom
   METHOD newFromObject
   METHOD newFromPointer
   METHOD selfDestruction
   METHOD setSelfDestruction

   DESTRUCTOR destroyObject

ENDCLASS

PROCEDURE destroyObject() CLASS QTime
   IF ::self_destruction
      ::delete()
   ENDIF
RETURN

// clang-format on

#pragma BEGINDUMP

#include <QtCore/Qt>

#ifndef __XHARBOUR__
#include <QtCore/QTime>
#endif

#include "qt5xhb_common.hpp"
#include "qt5xhb_macros.hpp"
#include "qt5xhb_utils.hpp"

#ifdef __XHARBOUR__
#include <QtCore/QTime>
#endif

#define GET_PTR_FROM_SELF(p) auto p = static_cast<QTime *>(Qt5xHb::itemGetPtrStackSelfItem())

HB_FUNC_STATIC(QTIME_NEW)
{
  if (ISNUMPAR(0)) {
    // QTime()
    auto obj = new QTime();
    Qt5xHb::returnNewObject(obj, true);
  } else if (ISBETWEEN(2, 4) && HB_ISNUM(1) && HB_ISNUM(2) && ISNUMORNIL(3) && ISNUMORNIL(4)) {
    // QTime(int h, int m, int s = 0, int ms = 0)
    auto obj = new QTime(PINT(1), PINT(2), OPINT(3, 0), OPINT(4, 0));
    Qt5xHb::returnNewObject(obj, true);
  } else {
    THROW_ERROR_3012();
  }
}

HB_FUNC_STATIC(QTIME_DELETE)
{
  GET_PTR_FROM_SELF(obj);
  DELETE_OBJECT(obj);
  RETURN_SELF();
}

// QTime addMSecs(int ms) const
HB_FUNC_STATIC(QTIME_ADDMSECS)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(1) && HB_ISNUM(1)) {
#endif
      RQTIME(obj->addMSecs(PINT(1)));
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      THROW_ERROR_3012();
    }
#endif
  }
}

// QTime addSecs(int s) const
HB_FUNC_STATIC(QTIME_ADDSECS)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(1) && HB_ISNUM(1)) {
#endif
      RQTIME(obj->addSecs(PINT(1)));
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      THROW_ERROR_3012();
    }
#endif
  }
}

// int elapsed() const
HB_FUNC_STATIC(QTIME_ELAPSED)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(0)) {
#endif
      RINT(obj->elapsed());
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      THROW_ERROR_3012();
    }
#endif
  }
}

// int hour() const
HB_FUNC_STATIC(QTIME_HOUR)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(0)) {
#endif
      RINT(obj->hour());
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      THROW_ERROR_3012();
    }
#endif
  }
}

// bool isNull() const
HB_FUNC_STATIC(QTIME_ISNULL)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(0)) {
#endif
      RBOOL(obj->isNull());
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      THROW_ERROR_3012();
    }
#endif
  }
}

HB_FUNC_STATIC(QTIME_ISVALID)
{
  if (ISNUMPAR(0)) {
    // bool isValid() const
    GET_PTR_FROM_SELF(obj);

    if (obj != nullptr) {
      RBOOL(obj->isValid());
    }
  } else if (ISBETWEEN(3, 4) && HB_ISNUM(1) && HB_ISNUM(2) && HB_ISNUM(3) && ISNUMORNIL(4)) {
    // static bool isValid(int h, int m, int s, int ms = 0)
    RBOOL(QTime::isValid(PINT(1), PINT(2), PINT(3), OPINT(4, 0)));
  } else {
    THROW_ERROR_3012();
  }
}

// int minute() const
HB_FUNC_STATIC(QTIME_MINUTE)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(0)) {
#endif
      RINT(obj->minute());
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      THROW_ERROR_3012();
    }
#endif
  }
}

// int msec() const
HB_FUNC_STATIC(QTIME_MSEC)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(0)) {
#endif
      RINT(obj->msec());
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      THROW_ERROR_3012();
    }
#endif
  }
}

// int msecsTo(const QTime &t) const
HB_FUNC_STATIC(QTIME_MSECSTO)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(1) && ISQTIME(1)) {
#endif
      RINT(obj->msecsTo(*PQTIME(1)));
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      THROW_ERROR_3012();
    }
#endif
  }
}

// int restart()
HB_FUNC_STATIC(QTIME_RESTART)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(0)) {
#endif
      RINT(obj->restart());
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      THROW_ERROR_3012();
    }
#endif
  }
}

// int second() const
HB_FUNC_STATIC(QTIME_SECOND)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(0)) {
#endif
      RINT(obj->second());
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      THROW_ERROR_3012();
    }
#endif
  }
}

// int secsTo(const QTime &t) const
HB_FUNC_STATIC(QTIME_SECSTO)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(1) && ISQTIME(1)) {
#endif
      RINT(obj->secsTo(*PQTIME(1)));
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      THROW_ERROR_3012();
    }
#endif
  }
}

// bool setHMS(int h, int m, int s, int ms = 0)
HB_FUNC_STATIC(QTIME_SETHMS)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISBETWEEN(3, 4) && HB_ISNUM(1) && HB_ISNUM(2) && HB_ISNUM(3) && ISNUMORNIL(4)) {
#endif
      RBOOL(obj->setHMS(PINT(1), PINT(2), PINT(3), OPINT(4, 0)));
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      THROW_ERROR_3012();
    }
#endif
  }
}

// void start()
HB_FUNC_STATIC(QTIME_START)
{
  GET_PTR_FROM_SELF(obj);

  if (obj != nullptr) {
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    if (ISNUMPAR(0)) {
#endif
      obj->start();
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
    } else {
      THROW_ERROR_3012();
    }
#endif
  }

  RETURN_SELF();
}

HB_FUNC_STATIC(QTIME_TOSTRING)
{
  if (ISNUMPAR(1) && HB_ISCHAR(1)) {
    // QString toString(const QString &format) const
    GET_PTR_FROM_SELF(obj);

    if (obj != nullptr) {
      RQSTRING(obj->toString(PQSTRING(1)));
    }
  } else if (ISBETWEEN(0, 1) && ISNUMORNIL(1)) {
    // QString toString(Qt::DateFormat format = Qt::TextDate) const
    GET_PTR_FROM_SELF(obj);

    if (obj != nullptr) {
      RQSTRING(obj->toString(HB_ISNIL(1) ? Qt::TextDate : PQT_DATEFORMAT(1)));
    }
  } else {
    THROW_ERROR_3012();
  }
}

// static QTime currentTime()
HB_FUNC_STATIC(QTIME_CURRENTTIME)
{
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
  if (ISNUMPAR(0)) {
#endif
    RQTIME(QTime::currentTime());
#ifndef QT5XHB_DONT_CHECK_PARAMETERS
  } else {
    THROW_ERROR_3012();
  }
#endif
}

HB_FUNC_STATIC(QTIME_FROMSTRING)
{
  if (ISBETWEEN(1, 2) && HB_ISCHAR(1) && ISNUMORNIL(2)) {
    // static QTime fromString(const QString &string, Qt::DateFormat format = Qt::TextDate)
    RQTIME(QTime::fromString(PQSTRING(1), HB_ISNIL(2) ? Qt::TextDate : PQT_DATEFORMAT(2)));
  } else if (ISNUMPAR(2) && HB_ISCHAR(1) && HB_ISCHAR(2)) {
    // static QTime fromString(const QString &string, const QString &format)
    RQTIME(QTime::fromString(PQSTRING(1), PQSTRING(2)));
  } else {
    THROW_ERROR_3012();
  }
}

HB_FUNC_STATIC(QTIME_NEWFROM)
{
  NEWFROM();
}

HB_FUNC_STATIC(QTIME_NEWFROMOBJECT)
{
  HB_FUNC_EXEC(QTIME_NEWFROM);
}

HB_FUNC_STATIC(QTIME_NEWFROMPOINTER)
{
  HB_FUNC_EXEC(QTIME_NEWFROM);
}

HB_FUNC_STATIC(QTIME_SELFDESTRUCTION)
{
  SELFDESTRUCTION();
}

HB_FUNC_STATIC(QTIME_SETSELFDESTRUCTION)
{
  SETSELFDESTRUCTION();
}

#pragma ENDDUMP
